In [7]:
import pandas as pd
import numpy as np

# 1. Create a null vector of size 10 but the fifth value which is 1.
z = np.zeros(10)
z[5]=1
z

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [9]:
# 2. Create a vector with values ranging from 10 to 49.
arr=np.arange(10,48)
arr


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47])

In [18]:
# 3. Create a 3x3 matrix with values ranging from 0 to 8
arr=np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
# 4. Find indices of non-zero elements from [1,2,0,0,4,0]
arr=np.array([1,2,0,0,4,0])
non_zero_arr=np.nonzero(arr)
non_zero_arr

(array([0, 1, 4], dtype=int64),)

In [24]:
# 5. Create a 10x10 array with random values and find the minimum and maximum values.
arr=np.random.rand(10,10)
arr
max_val=np.max(arr)
min_val=np.min(arr)
print("Minimum value:", min_val)
print("Maximum value:", max_val)

Minimum value: 0.006836582675909697
Maximum value: 0.9970086820479832


In [26]:
# 6. Create a random vector of size 30 and find the mean value.
arr=np.random.rand(30)
mean=np.mean(arr)
print("mean_val:",mean)

mean_val: 0.5540027766275112
